spring.application.name=MoodFlow

# Konfigurasi H2 Database
spring.datasource.url=jdbc:h2:mem:moodflowdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Mengaktifkan H2 Console (agar bisa diakses via browser saat aplikasi jalan)
spring.h2.console.enabled=true
# Path akses console: http://localhost:8080/h2-console
spring.h2.console.path=/h2-console

# Pengaturan Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
# Menampilkan SQL yang dijalankan di console (berguna untuk debugging)
spring.jpa.show-sql=true